server:
  port: 8080


demo:
  userName: lv

#??swagger 3?Spring boot???????
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userDB?serverTimezone=UTC
    username: root
    password: 1234

# 开启mp的日志（输出到控制台）
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl